-- Bipa — schema PostgreSQL
-- Tabelas essenciais usadas pelo app. Rodado idempotente na primeira execução
-- do setup e nas migrations (as declarações usam IF NOT EXISTS).
--
-- Comparado ao schema.sql (MariaDB):
--   AUTO_INCREMENT      → GENERATED BY DEFAULT AS IDENTITY
--   TINYINT(1)          → SMALLINT (mantém compat com o código que usa 0/1)
--   DOUBLE              → DOUBLE PRECISION
--   `nome`              → "nome" (mas geralmente não precisa — PG aceita sem aspas)
--   DATETIME            → TIMESTAMP
--   Sem CHARACTER SET/ENGINE (PG é UTF-8 e transacional por padrão)

-- ==========================================================================
-- CADASTROS
-- ==========================================================================

CREATE TABLE IF NOT EXISTS cad_empresa (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_empresa      VARCHAR(100),
  cep               VARCHAR(15),
  endereco          VARCHAR(100),
  bairro            VARCHAR(60),
  cidade            VARCHAR(60),
  uf                CHAR(2),
  email             VARCHAR(100),
  site              VARCHAR(100),
  telefone          VARCHAR(15),
  fax               VARCHAR(15),
  cpf_cpnj          VARCHAR(18),
  rg_ie             VARCHAR(16),
  im                VARCHAR(20),
  qtd_turnos        CHAR(1) NOT NULL DEFAULT '1',
  qtd_terminal      INTEGER DEFAULT 1,
  chave_liberacao   VARCHAR(21),
  max_desc          DOUBLE PRECISION,
  juros_atraso      DOUBLE PRECISION,
  txt_venda         TEXT,
  simbolo_monetario VARCHAR(5) DEFAULT 'R$',
  casas_decimais    INTEGER NOT NULL DEFAULT 2,
  inativo           SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cad_login_perfil (
  id_perfil     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_perfil   VARCHAR(60) NOT NULL,
  menu_options  TEXT,
  inativo       SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cad_login (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login         VARCHAR(60) NOT NULL,
  senha         VARCHAR(255),
  id_perfil     INTEGER,
  nome          VARCHAR(100),
  email         VARCHAR(100),
  telefone      VARCHAR(15),
  inativo       SMALLINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cad_login_login ON cad_login(login);
CREATE INDEX IF NOT EXISTS idx_cad_login_perfil ON cad_login(id_perfil);

CREATE TABLE IF NOT EXISTS cad_produtos_tipo (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_tipo  VARCHAR(80) NOT NULL,
  inativo    SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cad_produtos (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_produto   VARCHAR(200) NOT NULL,
  cod_barra      VARCHAR(30),
  unidade        VARCHAR(10),
  inf_adicional  VARCHAR(100),
  id_tipo        INTEGER,
  vr_compra      DOUBLE PRECISION DEFAULT 0,
  vr_venda       DOUBLE PRECISION DEFAULT 0,
  vr_venda_2     DOUBLE PRECISION DEFAULT 0,
  estoque        DOUBLE PRECISION DEFAULT 0,
  min_estoque    DOUBLE PRECISION DEFAULT 0,
  fracionado     SMALLINT DEFAULT 0,
  ncm            VARCHAR(10),
  cfop           VARCHAR(5),
  cst_csosn      VARCHAR(4),
  cest           VARCHAR(10),
  origem_produto SMALLINT,
  inativo        SMALLINT DEFAULT 0,
  data_criacao   TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_barra ON cad_produtos(cod_barra);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_tipo ON cad_produtos(id_tipo);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_nome ON cad_produtos(nome_produto);

CREATE TABLE IF NOT EXISTS cad_fornecedores (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_fornecedor   VARCHAR(150) NOT NULL,
  cpf_cnpj          VARCHAR(20),
  contato           VARCHAR(60),
  telefone          VARCHAR(20),
  email             VARCHAR(100),
  endereco          VARCHAR(150),
  cidade            VARCHAR(60),
  uf                CHAR(2),
  cep               VARCHAR(15),
  observacao        TEXT,
  inativo           SMALLINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cad_fornecedores_cnpj ON cad_fornecedores(cpf_cnpj);

CREATE TABLE IF NOT EXISTS cad_produtos_fornecedores (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto     INTEGER NOT NULL,
  id_fornecedor  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_fornecedores_produto ON cad_produtos_fornecedores(id_produto);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_fornecedores_forn ON cad_produtos_fornecedores(id_fornecedor);

CREATE TABLE IF NOT EXISTS cad_produtos_codigos (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto     INTEGER NOT NULL,
  tipo           VARCHAR(20) NOT NULL DEFAULT 'EAN',
  codigo         VARCHAR(50) NOT NULL,
  embalagem      VARCHAR(20),
  fator          DOUBLE PRECISION NOT NULL DEFAULT 1,
  id_fornecedor  INTEGER,
  util_venda     SMALLINT DEFAULT 1,
  preferencial   SMALLINT DEFAULT 0,
  data_inicio    DATE,
  inativo        SMALLINT DEFAULT 0,
  data_criacao   TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_codigos_produto ON cad_produtos_codigos(id_produto);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_codigos_codigo ON cad_produtos_codigos(codigo);

CREATE TABLE IF NOT EXISTS cad_produtos_promocao (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto         INTEGER NOT NULL,
  descricao          VARCHAR(100),
  vr_promocao        DOUBLE PRECISION NOT NULL DEFAULT 0,
  quantidade_minima  INTEGER NOT NULL DEFAULT 1,
  data_inicio        DATE NOT NULL,
  data_fim           DATE,
  inativo            SMALLINT DEFAULT 0,
  data_criacao       TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cad_produtos_promocao_produto ON cad_produtos_promocao(id_produto);

CREATE TABLE IF NOT EXISTS cad_clientes (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_cliente   VARCHAR(150) NOT NULL,
  cpf_cnpj       VARCHAR(20),
  telefone       VARCHAR(20),
  celular        VARCHAR(20),
  email          VARCHAR(100),
  endereco       VARCHAR(150),
  cidade         VARCHAR(60),
  uf             CHAR(2),
  cep            VARCHAR(15),
  cod_barra      VARCHAR(30),
  observacao     TEXT,
  inativo        SMALLINT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cad_clientes_cpf ON cad_clientes(cpf_cnpj);
CREATE INDEX IF NOT EXISTS idx_cad_clientes_nome ON cad_clientes(nome_cliente);

CREATE TABLE IF NOT EXISTS cad_modo_lancamento (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modo_lancamento   VARCHAR(60) NOT NULL,
  protegido         CHAR(1),
  inativo           SMALLINT DEFAULT 0
);

-- Seed inicial das formas de pagamento protegidas
INSERT INTO cad_modo_lancamento (modo_lancamento, protegido)
SELECT 'DINHEIRO', 'S'
WHERE NOT EXISTS (SELECT 1 FROM cad_modo_lancamento WHERE UPPER(modo_lancamento) = 'DINHEIRO');
INSERT INTO cad_modo_lancamento (modo_lancamento, protegido)
SELECT 'CARTÃO DÉBITO', 'S'
WHERE NOT EXISTS (SELECT 1 FROM cad_modo_lancamento WHERE UPPER(modo_lancamento) = 'CARTÃO DÉBITO');
INSERT INTO cad_modo_lancamento (modo_lancamento, protegido)
SELECT 'CARTÃO CRÉDITO', 'S'
WHERE NOT EXISTS (SELECT 1 FROM cad_modo_lancamento WHERE UPPER(modo_lancamento) = 'CARTÃO CRÉDITO');

CREATE TABLE IF NOT EXISTS cad_conta (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conta_descricao   VARCHAR(80) NOT NULL,
  saldo_inicial     DOUBLE PRECISION DEFAULT 0,
  inativo           SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cad_planejamento (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plane_cod         VARCHAR(20),
  plane_descricao   VARCHAR(120) NOT NULL,
  plane_tipo        CHAR(1),
  inativo           SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cad_lancamentos (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_planejamento     INTEGER,
  id_conta            INTEGER,
  id_cliente          INTEGER,
  id_fornecedor       INTEGER,
  data_vencimento     DATE,
  data_confirmacao    DATE,
  vr_parcela          DOUBLE PRECISION NOT NULL DEFAULT 0,
  historico           VARCHAR(255),
  documento           VARCHAR(50),
  parcela             INTEGER,
  total_parcelas      INTEGER,
  status              CHAR(1),
  observacao          TEXT,
  data_lancamento     TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cad_lancamentos_venc ON cad_lancamentos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_cad_lancamentos_plan ON cad_lancamentos(id_planejamento);

-- ==========================================================================
-- MOVIMENTO
-- ==========================================================================

CREATE TABLE IF NOT EXISTS mv_caixa (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_abertura      DATE NOT NULL,
  hora_abertura      TIME,
  data_fechamento    DATE,
  hora_fechamento    TIME,
  vr_abertura        DOUBLE PRECISION DEFAULT 0,
  vr_fechamento      DOUBLE PRECISION,
  id_login           INTEGER,
  terminal           VARCHAR(10) DEFAULT '01',
  turno              CHAR(1) DEFAULT '1',
  status_caixa       CHAR(1) NOT NULL DEFAULT 'A'
);
CREATE INDEX IF NOT EXISTS idx_mv_caixa_status ON mv_caixa(status_caixa);
CREATE INDEX IF NOT EXISTS idx_mv_caixa_data ON mv_caixa(data_abertura);

CREATE TABLE IF NOT EXISTS mv_caixa_movimento (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_caixa     INTEGER NOT NULL,
  tipo         CHAR(1) NOT NULL,
  descricao    VARCHAR(255),
  valor        DOUBLE PRECISION NOT NULL DEFAULT 0,
  data_hora    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  id_login     INTEGER
);
CREATE INDEX IF NOT EXISTS idx_mv_caixa_movimento_caixa ON mv_caixa_movimento(id_caixa);

CREATE TABLE IF NOT EXISTS mv_vendas (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  controle_venda     VARCHAR(20),
  data_venda         DATE NOT NULL,
  hora_venda         TIME,
  id_cliente         INTEGER,
  id_login           INTEGER,
  id_caixa           INTEGER,
  terminal           VARCHAR(10) DEFAULT '01',
  vr_total           DOUBLE PRECISION NOT NULL DEFAULT 0,
  vr_desconto        DOUBLE PRECISION DEFAULT 0,
  vr_troco           DOUBLE PRECISION DEFAULT 0,
  observacao         TEXT,
  status_venda       CHAR(1) DEFAULT 'F'
);
CREATE INDEX IF NOT EXISTS idx_mv_vendas_data ON mv_vendas(data_venda);
CREATE INDEX IF NOT EXISTS idx_mv_vendas_cliente ON mv_vendas(id_cliente);

CREATE TABLE IF NOT EXISTS mv_vendas_movimento (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venda       INTEGER NOT NULL,
  id_produto     INTEGER NOT NULL,
  quant          DOUBLE PRECISION NOT NULL DEFAULT 1,
  valor          DOUBLE PRECISION NOT NULL DEFAULT 0,
  vr_desconto    DOUBLE PRECISION DEFAULT 0,
  vr_total       DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_mv_vendas_movimento_venda ON mv_vendas_movimento(id_venda);
CREATE INDEX IF NOT EXISTS idx_mv_vendas_movimento_produto ON mv_vendas_movimento(id_produto);

CREATE TABLE IF NOT EXISTS mv_estoque_historico (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produto        INTEGER NOT NULL,
  id_fornecedor     INTEGER,
  modo_lancamento   INTEGER,
  data_entrada      DATE NOT NULL,
  quantidade        DOUBLE PRECISION NOT NULL DEFAULT 0,
  valor             DOUBLE PRECISION DEFAULT 0,
  nota_entrada      VARCHAR(50),
  tipo              CHAR(1) DEFAULT 'N',
  motivo            VARCHAR(255),
  id_login          INTEGER,
  data_lancamento   TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_mv_estoque_historico_produto ON mv_estoque_historico(id_produto);
CREATE INDEX IF NOT EXISTS idx_mv_estoque_historico_data ON mv_estoque_historico(data_entrada);

CREATE TABLE IF NOT EXISTS nfce_emitidas (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venda          INTEGER NOT NULL,
  controle_venda    VARCHAR(14) NOT NULL,
  ref_externa       VARCHAR(50) NOT NULL,
  provider          VARCHAR(30) DEFAULT 'focusnfe',
  ambiente          VARCHAR(15) DEFAULT 'homologacao',
  status            VARCHAR(30) DEFAULT 'pendente',
  chave_nfe         VARCHAR(60),
  numero            INTEGER,
  serie             INTEGER,
  protocolo         VARCHAR(30),
  url_danfe         TEXT,
  url_xml           TEXT,
  qrcode_url        TEXT,
  mensagem_sefaz    TEXT,
  payload_json      TEXT,
  response_json     TEXT,
  data_emissao      TIMESTAMP,
  data_atualizacao  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_nfce_emitidas_ref ON nfce_emitidas(ref_externa);
CREATE INDEX IF NOT EXISTS idx_nfce_emitidas_venda ON nfce_emitidas(id_venda);
CREATE INDEX IF NOT EXISTS idx_nfce_emitidas_status ON nfce_emitidas(status);
CREATE INDEX IF NOT EXISTS idx_nfce_emitidas_chave ON nfce_emitidas(chave_nfe);
